Removed comments
Using getFragmentManager().putFragment() didn't work well since the target fragment is associated with Tab's FragmentTransaction.

Process: com.akisute.yourwifi.app, PID: 5215
    java.lang.IllegalStateException: Fragment MapFragment{42627300} is not currently in the FragmentManager
            at android.app.FragmentManagerImpl.putFragment(FragmentManager.java:564)
            at com.akisute.yourwifi.app.MainActivity.onSaveInstanceState(MainActivity.java:78)